engines:
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
    config:
      rulesets: "codesize,unusedcode,naming,design"
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - php
ratings:
   paths:
   - src/Alientronics/FleetanyWebAdmin/Controllers/**
   - src/Alientronics/FleetanyWebAdmin/Repositories/**
   - "**.php"